WiredBrainCoffeeAdmin/Components/ProductListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Components
{
    public class ProductListViewComponent : ViewComponent
    {
        private IProductRepository productRepo;

        public ProductListViewComponent(IProductRepository productRepository)
        {
            this.productRepo = productRepository;
        }

        public IViewComponentResult Invoke(int count)
        {
            var items = productRepo.GetAll();
            if(count > 0)
            {
                return View(items.Take(count).ToList());
            }
            
            return View(items);
        }
    }
}

WiredBrainCoffeeAdmin/Pages/AddProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class AddProductModel : PageModel
    {
        private WiredBrainContext _context;
        private IWebHostEnvironment _environment;

        public List<Product> Products { get; set; }

        public AddProductModel(WiredBrainContext context,
            IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        [BindProperty]
        public Product Product { get; set; }

        [FromRoute]
        public int Id { get; set; }

        public void OnGet()
        {
            if (Id != 0)
            {
                Product = _context.Products.FirstOrDefault(x => x.Id == Id);
            }
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                if(Id == 0)
                {
                    Product.ImageFile = Product.Upload.FileName;
                    Product.Category = Product.Category;
                    _context.Products.Add(Product);
                    _context.SaveChanges();

                    var file = Path.Combine(_environment.ContentRootPath, "wwwroot/images/menu", Product.Upload.FileName);
                    using (var fileStream = new FileStream(file, FileMode.Create))
                    {
                        await Product.Upload.CopyToAsync(fileStream);
                    }
                } 
                else
                {
                    var savedItem = _context.Products.FirstOrDefault(x => x.Id == Id);

                    savedItem.Name = Product.Name;
                    savedItem.Description = Product.Description;
                    savedItem.ShortDescription = Product.ShortDescription;
                    savedItem.Category = Product.Category;
                    savedItem.Price = Product.Price;
                    savedItem.ImageFile = Product.Upload is not null ? Product.Upload.FileName : savedItem.ImageFile;
                    _context.SaveChanges();

                    if (Product.Upload != null)
                    {
                        var file = Path.Combine(_environment.ContentRootPath, "wwwroot/images/menu", Product.Upload.FileName);
                        using (var fileStream = new FileStream(file, FileMode.Create))
                        {
                            await Product.Upload.CopyToAsync(fileStream);
                        }
                    }
                }

                return RedirectToPage("ViewProducts");
            }

            return Page();
        }
    }
}

WiredBrainCoffeeAdmin/Pages/EditProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class EditProductModel : PageModel
    {
        private WiredBrainContext _context;
        private IWebHostEnvironment _environment;

        public List<Product> Products { get; set; }

        public EditProductModel(WiredBrainContext context,
            IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        [BindProperty]
        public Product Product { get; set; }

        [FromRoute]
        public int Id { get; set; }

        public void OnGet()
        {
            if (Id != 0)
            {
                Product = _context.Products.FirstOrDefault(x => x.Id == Id);
            }
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var savedItem = _context.Products.FirstOrDefault(x => x.Id == Id);

                savedItem.Name = Product.Name;
                savedItem.Description = Product.Description;
                savedItem.ShortDescription = Product.ShortDescription;
                savedItem.Category = Product.Category;
                savedItem.Price = Product.Price;
                savedItem.ImageFile = Product.Upload is not null ? Product.Upload.FileName : savedItem.ImageFile;
                _context.SaveChanges();

                if (Product.Upload != null)
                {
                    var file = Path.Combine(_environment.ContentRootPath, "wwwroot/images/menu", Product.Upload.FileName);
                    using (var fileStream = new FileStream(file, FileMode.Create))
                    {
                        await Product.Upload.CopyToAsync(fileStream);
                    }
                }

                return RedirectToPage("ViewProducts");
            }

            return Page();
        }
    }
}

WiredBrainCoffeeAdmin/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WiredBrainCoffeeAdmin.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WiredBrainCoffeeAdmin/Pages/Help.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.Design;
using WiredBrainCoffeeAdmin.Data;
using WiredBrainCoffeeAdmin.Data.Models;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class HelpModel : PageModel
    {
        public async Task<IActionResult> OnGet()
        {
            return Page();
        }
    }
}

WiredBrainCoffeeAdmin/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using System.Text;
using System.Text.Json;
using System;
using System.IO;
using System.Threading.Tasks;
using WiredBrainCoffeeAdmin.Data.Models;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IHttpClientFactory factory;

        public IDictionary<string, string> OrderStats { get; set; }

        public List<SurveyItem> SurveyResults { get; set; }
        private IWebHostEnvironment webEnv;

        public IndexModel(ILogger<IndexModel> logger, IHttpClientFactory httpFactory,
            IWebHostEnvironment environment)
        {
            _logger = logger;
            this.factory = httpFactory;
            this.webEnv = environment;
        }

        public async Task<IActionResult> OnGet()
        {
            var client = this.factory.CreateClient();
            var response = await client
                .GetAsync("https://wiredbraincoffeeadmin.azurewebsites.net/api/orderStats");

            var responseData = await response.Content.ReadAsStringAsync();
            OrderStats = JsonSerializer.Deserialize<IDictionary<string, string>>(responseData);

            var rawJson = System.IO.File
                .ReadAllText(Path.Combine(webEnv.ContentRootPath, "wwwroot/sampledata/survey.json"));

            SurveyResults = JsonSerializer.Deserialize<List<SurveyItem>>(rawJson);

            return Page();
        }
    }
}

WiredBrainCoffeeAdmin/Pages/Products/AddProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Pages.Products
{
    public class AddProductModel : PageModel
    {
        [BindProperty]
        public Product NewProduct { get; set; }

        public void OnGet()
        {
            
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                // Save product to database
                var productName = NewProduct.Name;

                return RedirectToPage("ViewAllProducts");
            }

            return Page();
        }
    }
}

WiredBrainCoffeeAdmin/Pages/Products/EditProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WiredBrainCoffeeAdmin.Pages.Products
{
    public class EditProductModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WiredBrainCoffeeAdmin/Pages/Products/ViewAllProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WiredBrainCoffeeAdmin.Pages.Products
{
    public class ViewAllProductsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WiredBrainCoffeeAdmin/Pages/ViewProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class ViewProductsModel : PageModel
    {
        private WiredBrainContext _context;

        public List<Product> Products { get; set; }

        public ViewProductsModel(WiredBrainContext context)
        {
            _context = context;
        }
        public void OnGet()
        {
            Products = _context.Products.ToList();
        }
    }
}

WiredBrainCoffeeAdmin/Pages/AddProduct.cshtml
@page "/menu/add/{id:int?}"
@model WiredBrainCoffeeAdmin.Pages.AddProductModel

<h1 class="h2">Add New Menu Item</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        @if (!String.IsNullOrEmpty(Model.Product?.ImageFile))
        {
            <img class="item-preview" src="~/images/menu/@Model.Product?.ImageFile" />
        }
        <form method="post" class="add-edit-form" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label class="form-label">Name</label>
                <input type="text" asp-for="Product.Name" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Category</label>
                <select class="form-control" asp-for="Product.Category">
                    <option value="Coffee">Coffee</option>
                    <option value="Food">Food</option>
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">Short Description</label>
                <input type="text" asp-for="Product.ShortDescription" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Long Description</label>
                <textarea asp-for="Product.Description" class="form-control"></textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">Price</label>
                <input type="number" asp-for="Product.Price" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Image</label>
                <input type="file" asp-for="Product.Upload" class="form-control" />
            </div>
            <button type="submit" class="btn btn-success float-right">Submit</button>
        </form>
    </div>
    <div class="col-md-6">
        @Html.Partial("Info")
    </div>
</div>

WiredBrainCoffeeAdmin/Pages/EditProduct.cshtml
@page "/menu/edit/{id:int?}"
@model WiredBrainCoffeeAdmin.Pages.EditProductModel

<h1 class="h2">Edit Menu Item</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        @if (!String.IsNullOrEmpty(Model.Product?.ImageFile))
        {
            <img class="item-preview" src="~/images/menu/@Model.Product?.ImageFile" />
        }
        <form method="post" class="add-edit-form" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label class="form-label">Name</label>
                <input type="text" asp-for="Product.Name" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Category</label>
                <select class="form-control" asp-for="Product.Category">
                    <option value="Coffee">Coffee</option>
                    <option value="Food">Food</option>
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">Short Description</label>
                <input type="text" asp-for="Product.ShortDescription" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Long Description</label>
                <textarea asp-for="Product.Description" class="form-control"></textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">Price</label>
                <input type="number" asp-for="Product.Price" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Image</label>
                <input type="file" asp-for="Product.Upload" class="form-control" />
            </div>
            <button type="submit" class="btn btn-success float-right">Submit</button>
        </form>
    </div>
    <div class="col-md-6">
        @Html.Partial("Info")
    </div>
</div>

WiredBrainCoffeeAdmin/Pages/Help.cshtml
@page "/help"
@model WiredBrainCoffeeAdmin.Pages.HelpModel
@{
}

<h1>Request Help</h1>
<hr />

<div class="row">
    <div class="col-md-6">
        
    </div>
    <div class="col-md-6">
        
    </div>
</div>


@section RightFooter {
    <p>Call us at: 123-456-7890</p>
    <p>Hours of operation: 9am to 4pm</p>
}

WiredBrainCoffeeAdmin/Pages/HelpWidget.cshtml
<div class="card">
    <div class="card-header">
        Request Help
    </div>
    <div class="card-body">
        <h5 class="card-title">Contact our IT Team</h5>
        <p class="card-text">Having an issue with the site? Let us know!</p>
        <a asp-page="/help" class="btn btn-success">Request Help</a>
    </div>
</div>

WiredBrainCoffeeAdmin/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container-fluid dashboard">
    <h1>Welcome to Wired Brain Coffee!</h1>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <h2>Latest Survey Results</h2>
            <table class="table table-striped table-bordered">
                @foreach(var item in Model.SurveyResults)
                {
                    <tr>
                        <td>@item.Question</td>
                        <td>@item.Answer</td>
                    </tr>
                }
            </table>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    The Basics
                </div>
                <div class="card-body">
                    <p>Hello, today is @DateTime.Today.Date.ToString("MM/dd/yyyy").</p>
                    @{
                        var temperature = 55;
                    }
                    <p>The current temperature is @temperature degrees.</p>
                    @if(temperature < 60)
                    {
                        <p>We recommend a coat until it warms up</p>
                    }
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    Request Help
                </div>
                <div class="card-body">
                    <h5 class="card-title">Contact our IT Team</h5>
                    <p class="card-text">Having an issue with the site? Let us know!</p>
                    <a asp-page="help" class="btn btn-success">Request Help</a>
                </div>
            </div>
        </div>
    </div>
</div>

WiredBrainCoffeeAdmin/Pages/ProductForm.cshtml
@using WiredBrainCoffeeAdmin.Data
@model Product

<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="@Model.Name">Name</label>
        <input asp-for="@Model.Name" class="form-control" />
        <span asp-validation-for="@Model.Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.ShortDescription">Short Description</label>
        <input asp-for="@Model.ShortDescription" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Description">Description</label>
        <textarea asp-for="@Model.Description" class="form-control"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Price">Price</label>
        <input asp-for="@Model.Price" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Category">Category</label>
        <select asp-for="@Model.Category" class="form-control">
            <option value="Beverage">Beverage</option>
            <option value="Food">Food</option>
        </select>
    </div>
    @if(ViewContext.RouteData.Values["id"] is not null)
    {
        <div class="mb-3">
            <label asp-for="@Model.ImageFileName">Current Image</label>
            <input asp-for="@Model.ImageFileName" class="form-control" />
            <img src="~/images/menu/@Model.ImageFileName" />
        </div>
    }
    <div class="mb-3">
        <label asp-for="@Model.Upload">Image</label>
        <input asp-for="@Model.Upload" class="form-control" />
    </div>
    @if (ViewContext.RouteData.Values["id"] is not null)
    {
        <button asp-page-handler="edit" class="btn btn-success">Submit</button>
        <button asp-page-handler="delete" class="btn btn-danger float-end">Delete</button>
    } else
    {
        <button class="btn btn-success">Add</button>
    }
</form>

WiredBrainCoffeeAdmin/Pages/ViewProducts.cshtml
@page "/menu"
@model WiredBrainCoffeeAdmin.Pages.ViewProductsModel
<h1 class="h2">All Menu Items <a asp-page="AddProduct" class="btn-success btn float-end">Add New</a></h1>
<hr />
<div class="table-responsive">
    @await Component.InvokeAsync("ProductList")
</div>